Module 4. 1,2 - task
js-tasks-ru/jsbasic-20210225_danilazarudnyi pull request #7
Opened 2021-03-18 10:01 UTC by Lurker10

2021-03-18 10:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-18 19:04 UTC, SinimaWath requested changes

2021-03-18 19:04 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  for (let row = 0; row < table.rows.length; row++) {
Это же не row, а rowIndex. 

А то вот тут непонятно: `table.rows[row]`

2021-03-18 19:04 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  let list = document.createElement('ul');
Это const :)

2021-03-18 19:04 UTC, SinimaWath commented on 4-module/1-task/index.js
> +      list.innerHTML = list.innerHTML + `<li>${friend.firstName} ${friend.lastName}</li>`;
можно упростить до: `list.innerHTML += ...`

2021-03-19 17:35 UTC, SinimaWath requested changes

2021-03-19 17:35 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    if (tr.querySelector('td:last-child').getAttribute('data-available') == 'true') {
Интересное решение :) Думаю можно оставить.

2021-03-19 17:35 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      tr.setAttribute('hidden', 'true')
есть свойство hidden: `tr.hidden = true`, setAttribute, getAttribute - только не для стандартных атрибутов

2021-03-19 17:35 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    if (tr.querySelector('td:nth-child(3)').innerHTML == 'm') {
Везде по коду лучше заменить innerHTML на textContent:
- Если вдруг поменяют шрифт, допустим сделают жирный текст, через <strong></strong>. Эта проверка может сломаться

2021-03-19 17:35 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      tr.setAttribute('style', 'text-decoration: line-through')
Для стандартных атрибуттов всегда стоит использовать свойства:
`style.textDecoration`

2021-03-20 13:57 UTC, SinimaWath requested changes

2021-03-20 13:57 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    }
А зачем тут эта проверка? Если по коду ниже ты не используешь `button`?

2021-03-20 13:58 UTC, SinimaWath requested changes

2021-03-20 13:58 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  }
Вся таки, для упрощения кода, мне кажется, будет лучше написать через стрелочную функцию:

```
button.onclick = () => {

}
```

- просто из соображений, что меньше кода и более лаконично

2021-03-22 16:23 UTC, SinimaWath approved these changes

2021-03-22 16:23 UTC, merged