module 5. 3-task
js-tasks-ru/jsbasic-20210225_danilazarudnyi pull request #8
Opened 2021-03-23 10:44 UTC by Lurker10

2021-03-23 10:44 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 5-module/3-task/task.test.js — добавлен
```

2021-03-23 18:36 UTC, SinimaWath commented
Подтяни изменения из upstream плиз.

`git pull upstream master`

2021-03-23 18:38 UTC, SinimaWath requested changes

2021-03-23 18:38 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  });
1 - У тебя тут 2, почти полностью одинаковые функции. Давай попробуем выделить общую 
функционалность.

2 - анонимные функции, в качестве обработчика событий, не всегда хорошо. Так как их никогда не получиться отписать, от события. Лучше выдели в отдельную функцию

2021-03-25 19:08 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  });
Вот этот коммент посмотри :)

Подсказка: 
Раздели на 3 функции:
`next`, `previuos`, `update`

2021-03-25 19:09 UTC, SinimaWath requested changes

2021-03-25 19:09 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  };
все еще у тебя 2 эти функции одинаковые полностью почти.

Раздели на: `next`, `previous`, `update`.

2021-03-25 19:10 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    arrowRight.style.display = '';
Тут явно не хватает else

2021-03-25 19:10 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    arrowLeft.style.display = '';
Тут выглядит, что тоже нет else

2021-03-29 18:55 UTC, SinimaWath approved these changes

2021-03-29 18:55 UTC, merged